spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/oauth2/**,/login/**

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/books/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

        - id: wishlist-service
          uri: lb://WISHLIST-SERVICE
          predicates:
            - Path=/wishlist/**

        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/wallet/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**

        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/reviews/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.booknest.gateway.filter: INFO

app:
  jwt:
    secret: BookNestSecretKeyBookNestSecretKey123456
